name: smarttabungan_mobile
description: SmartTabungan Mobile App - Personal Finance Management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.0.5
  riverpod: ^2.4.9
  
  # HTTP Client
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Charts
  fl_chart: ^0.65.0
  
  # Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  
  # Biometric
  local_auth: ^2.1.7
  
  # Camera & File
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  
  # QR Code
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  
  # Location
  geolocator: ^10.1.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1
  permission_handler: ^11.1.0
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Form Validation
  form_validator: ^2.1.1
  
  # Date & Time
  table_calendar: ^3.0.9
  
  # Animations
  lottie: ^2.7.0
  
  # Icons
  font_awesome_flutter: ^10.6.0
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # Device Info
  device_info_plus: ^9.1.1
  
  # Package Info
  package_info_plus: ^4.2.0
  
  # Share
  share_plus: ^7.2.1
  
  # URL Launcher
  url_launcher: ^6.2.1
  
  # Crypto
  crypto: ^3.0.3
  
  # Logger
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.7
  
  # Code Generation
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - .env
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700 